name: Continuous Integration for Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci-frontend.yaml"
      - "ui/**"

env:
  NODE_VERSION: 22

jobs:
  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ui
      - name: Run build
        uses: borales/actions-yarn@v5
        with:
          cmd: build
          dir: ui

  lint:
    name: Lint TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ui
      - name: Run eslint
        uses: borales/actions-yarn@v5
        with:
          cmd: lint
          dir: ui
      - name: Run prettier
        uses: borales/actions-yarn@v5
        with:
          cmd: format-check
          dir: ui
